[package]
name = "messaging-wit-test"
version = "0.1.0"
authors = [""]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "messaging_wit_test"

[dependencies]
wit-bindgen = "0.11"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
